SET NAMES utf8mb4;

INSERT INTO news_items (slug, title, summary, category, content, image, published_at) VALUES
('seguranca-zero-trust-labs-2026','Laboratorio inicia trilha de Seguranca Zero Trust em redes academicas','Projeto interno publica guia de segmentacao, autenticacao forte e monitoramento continuo.','Seguranca','O laboratorio iniciou uma trilha aplicada de seguranca para ambientes academicos com foco em zero trust. A equipe esta validando politicas de acesso por contexto, segmentacao de servicos e telemetria centralizada para resposta rapida a incidentes. O material inclui boas praticas para alunos, docentes e administradores de infraestrutura.','/assets/images/news/seguranca-zero-trust-labs-2026.svg','2026-04-13 09:00:00'),
('criptografia-pos-quantica-piloto-2026','Grupo de Criptografia testa assinaturas pos-quanticas em servicos web','Equipe avalia impacto de desempenho e compatibilidade de algoritmos resistentes a ataques quanticos.','Criptografia','Pesquisadores e estudantes iniciaram um piloto com mecanismos de criptografia pos-quantica para assinatura e troca de chaves. O objetivo e mapear custos computacionais, requisitos de migracao e estrategias de interoperabilidade com sistemas atuais. Os resultados preliminares orientarao recomendacoes para adocao progressiva no departamento.','/assets/images/news/criptografia-pos-quantica-piloto-2026.svg','2026-04-13 09:15:00'),
('sistemas-computacao-observabilidade-2026','Nova bancada de Sistemas de Computacao reforca observabilidade de desempenho','Infraestrutura adiciona coleta de metricas de CPU, memoria e I/O para analise comparativa de workloads.','Sistemas de Computacao','A nova bancada de sistemas de computacao foi preparada para estudos de desempenho em diferentes cargas de trabalho. O ambiente integra monitoramento detalhado de recursos e trilhas de experimentos reproduziveis para disciplinas e projetos de pesquisa. A iniciativa melhora a analise de gargalos e a documentacao tecnica de resultados.','/assets/images/news/sistemas-computacao-observabilidade-2026.svg','2026-04-13 09:30:00'),
('criptomoedas-auditoria-onchain-2026','Projeto de Criptomoedas publica roteiro de auditoria on-chain para estudantes','Documento apresenta verificacao de contratos, rastreio de transacoes e analise de risco em redes abertas.','Criptomoedas','O laboratorio publicou um roteiro pratico para auditoria on-chain em projetos de criptomoedas. O conteudo cobre leitura de eventos, validacao de fluxos financeiros e criterios de seguranca para contratos inteligentes. A proposta apoia atividades de extensao, monitoria e formacao tecnica em blockchain.','/assets/images/news/criptomoedas-auditoria-onchain-2026.svg','2026-04-13 09:45:00'),
('eletronica-computacao-fpga-lab-2026','Modulo de Eletronica em Computacao inclui prototipagem com FPGA no laboratorio','Turmas passam a desenvolver pipelines digitais para aplicacoes de visao e processamento de sinais.','Eletronica em Computacao','A disciplina de eletronica em computacao ganhou um modulo pratico de prototipagem com FPGA. Os estudantes desenvolverao blocos digitais para aceleracao de tarefas de processamento e comunicacao entre perifericos. A mudanca amplia a integracao entre teoria de hardware e implementacao real em laboratorio.','/assets/images/news/eletronica-computacao-fpga-lab-2026.svg','2026-04-13 10:00:00'),
('sistemas-operacionais-kernel-lab-2026','Trilha de Sistemas Operacionais avanca com laboratorio de kernel e isolamento','Atividades abordam escalonamento, memoria virtual e seguranca por namespaces e cgroups.','Sistemas Operacionais','A nova trilha de sistemas operacionais combina aulas teoricas com experimentos de kernel em ambiente controlado. As praticas incluem observacao de processos, politicas de escalonamento e tecnicas de isolamento de servicos. O objetivo e aproximar os conceitos centrais de SO das demandas atuais de infraestrutura.','/assets/images/news/sistemas-operacionais-kernel-lab-2026.svg','2026-04-13 10:15:00'),
('sistemas-distribuidos-consenso-raft-2026','Equipe valida cenarios de consenso Raft em disciplina de Sistemas Distribuidos','Experimentos simulam falhas de rede, eleicao de lider e recuperacao de estado em clusters.','Sistemas Distribuidos','A disciplina de sistemas distribuidos iniciou uma sequencia de experimentos sobre consenso com Raft. Os cenarios incluem perda parcial de conectividade, reintegracao de nos e verificacao de consistencia. A atividade fortalece a compreensao de tolerancia a falhas em aplicacoes de servico critico.','/assets/images/news/sistemas-distribuidos-consenso-raft-2026.svg','2026-04-13 10:30:00'),
('seguranca-resposta-incidentes-soc-2026','Laboratorio organiza simulado de resposta a incidentes com mini SOC academico','Acao integra coleta de logs, priorizacao de alertas e protocolos de comunicacao tecnica.','Seguranca','Foi realizado um simulado de resposta a incidentes com foco em deteccao e tratamento coordenado de eventos de seguranca. O exercicio reuniu estudantes e equipe tecnica para triagem de alertas, analise forense inicial e plano de contencao. A iniciativa apoia a maturidade operacional do ambiente academico.','/assets/images/news/seguranca-resposta-incidentes-soc-2026.svg','2026-04-13 10:45:00'),
('criptografia-assinaturas-digitais-campus-2026','Piloto de assinaturas digitais amplia uso de Criptografia em fluxos administrativos','Processo adota validacao criptografica para documentos de laboratorio e registros internos.','Criptografia','Um piloto de assinaturas digitais foi iniciado para fortalecer autenticidade e integridade de documentos do laboratorio. A abordagem utiliza criptografia assimetrica e trilhas de verificacao para reduzir risco de alteracao indevida. A experiencia servira de base para expansao em outros fluxos administrativos do departamento.','/assets/images/news/criptografia-assinaturas-digitais-campus-2026.svg','2026-04-13 11:00:00'),
('sistemas-distribuidos-edge-cidades-2026','Projeto de Sistemas Distribuidos em edge computing abre nova frente de pesquisa aplicada','Grupo investiga processamento proximo da fonte de dados para reduzir latencia em cenarios urbanos.','Sistemas Distribuidos','Foi aberta uma frente de pesquisa em sistemas distribuidos voltada a edge computing para cenarios de cidades conectadas. O foco esta em distribuicao de carga, sincronizacao eventual e continuidade de servico sob conectividade variavel. A linha pretende gerar prototipos com impacto direto em aplicacoes de monitoramento urbano.','/assets/images/news/sistemas-distribuidos-edge-cidades-2026.svg','2026-04-13 11:15:00')
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    summary = VALUES(summary),
    category = VALUES(category),
    content = VALUES(content),
    image = VALUES(image),
    published_at = VALUES(published_at);
